language: node_js
node_js:
  - "8.9.0"

branches:
  only:
  - master

jobs:
  include:
  - stage: "install"
    script: "npm install"
  - stage: "build"
    script: "npm run build"
  - stage: "test"
    script: "npm run test"
  - stage: "release"
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: npm run semantic-release